name: Linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  standardrb:
    name: StandardRB Check Action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run StandardRB
        run: bin/standardrb
