name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Run Rspec
      run: bin/test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
